Async functions cannot return objects with a callable `then` property as JavaScript aggressively flattens promises.

```ts
class A {
  async test() {
    return {
      then() { }
    }
  }
}
```

The best fix for this error is to rename the `then` method on the object you are returning to something else. `chain` or `map` might be appropriate.

Note that in TS3.5.1, TypeScript will **not** complain about this equally wrong code. Calling `new A().test()` will result in a `Promise` which never resolves.

```ts
class A {
  test() {
    return Promise.resolve({
      then() { }
    })
  }
}
```

### See also

- [StackOverflow - Typescript error when function return type is Promise<{ then: () => void }>](https://stackoverflow.com/questions/47111363/typescript-error-when-function-return-type-is-promise-then-void)
- [StackOverflow - Fulfill (don't resolve) promise with another promise](https://stackoverflow.com/questions/32168194/fulfill-dont-resolve-promise-with-another-promise)
- [Monads for the Rest of Us - Why Promises are not Monads](https://gist.github.com/fatcerberus/beae4d15842071eab24fca2f0740c2ef#monads-its-the-law)
- [MDN - `Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
